issue:
ios:
android:
title:
author:
  id:
  login:
description:
resources:
playgrounds:
  js:
    url:
    author:
      id:
      login:
      date:
    contributor:
      id:
      login:
      date:
  ng:
    url:
    author:
      id:
      login:
      date:
    contributor:
      id:
      login:
      date:
  tsc:
    url:
    author:
      id:
      login:
      date:
    contributor:
      id:
      login:
      date:
  vue:
    url:
    author:
      id:
      login:
      date:
    contributor:
      id:
      login:
      date:
  react:
    url:
    author:
      id:
      login:
      date:
    contributor:
      id:
      login:
      date:
  svelte:
    url:
    author:
      id:
      login:
      date:
    contributor:
      id:
      login:
      date: