issue:
ios:
android:
title:
author: &author
  id: 
  login: 
  avatar:
  url: 
  date:
description: 
resources: 
playgrounds: 
  js:
    flavour: "JavaScript"
    url:
    author: *author
    contributor:
      id:
      login:
      avatar:
      url:
      date:
  ng:
    flavour: "Angular"
    url:
    author: *author
    contributor:
      id:
      login:
      avatar:
      url:
      date:
  tsc:
    flavour: "TypeScript"
    url:
    author: *author
    contributor:
      id:
      login:
      avatar:
      url:
      date:
  vue:
    flavour: "Vue"
    url:
    author: *author
    contributor:
      id:
      login:
      avatar:
      url:
      date:
  react:
    flavour: "React"
    url:
    author: *author
    contributor:
      id:
      login:
      avatar:
      url:
      date:
  svelte:
    flavour: "Svelte"
    url:
    author: *author
    contributor:
      id:
      login:
      avatar:
      url:
      date: