issue:
ios:
android:
title:
author:
  id:
  login:
  avatar:
  url:
  date:
description:
resources:
playgrounds:
  js:
    flavour: "JavaScript"
    url:
    author:
      id:
      login:
      url:
      date:
    contributor:
      id:
      login:
      url:
      date:
  ng:
    flavour: "Angular"
    url:
    author:
      id:
      login:
      url:
      date:
    contributor:
      id:
      login:
      url:
      date:
  tsc:
    flavour: "TypeScript"
    url:
    author:
      id:
      login:
      url:
      date:
    contributor:
      id:
      login:
      url:
      date:
  vue:
    flavour: "Vue"
    url:
    author:
      id:
      login:
      url:
      date:
    contributor:
      id:
      login:
      url:
      date:
  react:
    flavour: "React"
    url:
    author:
      id:
      login:
      url:
      date:
    contributor:
      id:
      login:
      url:
      date:
  svelte:
    flavour: "Svelte"
    url:
    author:
      id:
      login:
      url:
      date:
    contributor:
      id:
      login:
      url:
      date: