on: [issue_comment]

jobs:
  world:
    runs-on: ubuntu-latest
    name: Reply
    steps:
      - uses: actions/checkout@v1
      - name: Reply action
        id: reply
        if: ${{ github.context.payload.body == "Hello" }}
        uses: ./.github/action
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Action setup
  #       id: hello
  #       uses: ./.github/action
  #       with:
  #         who-to-greet: 'Mona the Octocat'
  #     - name: Get the output time
  #       run: echo "The time was ${{ steps.hello.outputs.time }}"