on: 
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

env:
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  project:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[project]')
    name: Project
    steps:
      - uses: actions/checkout@v2
      - name: Project Submission
        id: project
        uses: ./.github/action
      - name: Build README
        id: readme
        if: startsWith(steps.project.outputs.status, 'ready')
        uses: ./.github/action/readme
      - name: Add & Commit
        # if: there's a new project file to add to the remote repo master branch
        # See https://github.com/marketplace/actions/add-commit for details
        uses: EndBug/add-and-commit@v4.4.0
        with:
          author_name: ${{github.context.payload.login}} 
          author_email: ${{ format('Hi {0}', github.context.payload.sender.login) }}
          message: 'New project added'
          

