on: 
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  world:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[project]')
    name: Reply
    steps:
      - uses: actions/checkout@v1
      - name: Reply action
        id: reply
        uses: ./.github/action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Action setup
  #       id: hello
  #       uses: ./.github/action
  #       with:
  #         who-to-greet: 'Mona the Octocat'
  #     - name: Get the output time
  #       run: echo "The time was ${{ steps.hello.outputs.time }}"