on: 
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  world:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[project]')
    name: Reply
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SSH: ${{ secrets.ssh }}
    steps:
      - uses: actions/checkout@v1
      - name: Reply action
        id: reply
        uses: ./.github/action
      - name: Add & Commit
        # if: there's a new project file to add to the remote repo master branch
        # See https://github.com/marketplace/actions/add-commit for details
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: 'New project added'
          

